### ISSUE TITLE
自行编译的程序闪退

### ISSUE THREAD

**Issue by rarnu** [codehz/container#4]
直接在AS里导入项目，可以编译成功，kotlin，java 和 jni 部分均是成功的，启动后双开微信，会报以下错误。
能否告知正确的编译方式，特别是 X.patch 要如何使用。

03-08 01:18:52.899: E/DatabaseUtils(4767): Writing exception to parcel
03-08 01:18:52.899: E/DatabaseUtils(4767): java.lang.IllegalStateException: Token is exist!
03-08 01:18:52.899: E/DatabaseUtils(4767): 	at com.lody.virtual.client.VClientImpl.initProcess(VClientImpl.java:141)
03-08 01:18:52.899: E/DatabaseUtils(4767): 	at com.lody.virtual.client.stub.StubContentProvider.initProcess(StubContentProvider.java:35)
03-08 01:18:52.899: E/DatabaseUtils(4767): 	at com.lody.virtual.client.stub.StubContentProvider.call(StubContentProvider.java:22)
03-08 01:18:52.899: E/DatabaseUtils(4767): 	at android.content.ContentProvider$Transport.call(ContentProvider.java:398)
03-08 01:18:52.899: E/DatabaseUtils(4767): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
03-08 01:18:52.899: E/DatabaseUtils(4767): 	at android.os.Binder.execTransact(Binder.java:467)
03-08 01:18:52.906: E/AndroidRuntime(6328): FATAL EXCEPTION: main
03-08 01:18:52.906: E/AndroidRuntime(6328): Process: one.codehz.container, PID: 6328
03-08 01:18:52.906: E/AndroidRuntime(6328): java.lang.IllegalStateException: Token is exist!
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at android.os.Parcel.readException(Parcel.java:1628)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at android.os.Parcel.readException(Parcel.java:1573)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at com.lody.virtual.server.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:1131)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at java.lang.reflect.Method.invoke(Native Method)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at com.lody.virtual.client.ipc.LocalProxyUtils$1.invoke(LocalProxyUtils.java:28)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at $Proxy4.startActivity(Unknown Source)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at com.lody.virtual.client.ipc.VActivityManager.startActivity(VActivityManager.java:75)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at com.lody.virtual.client.ipc.VActivityManager.startActivity(VActivityManager.java:89)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at one.codehz.container.VLoadingActivity$onCreate$1.run(VLoadingActivity.kt:39)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at android.os.Handler.handleCallback(Handler.java:739)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at android.os.Looper.loop(Looper.java:152)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at android.app.ActivityThread.main(ActivityThread.java:5507)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at java.lang.reflect.Method.invoke(Native Method)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-08 01:18:52.906: E/AndroidRuntime(6328): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
03-08 01:18:52.912: E/ActivityThread(6328): Failed to find provider info for net.oneplus.odm.provider.PayloadProvider
03-08 01:18:52.912: E/AbstractTracker(6328): Unknown URL content://net.oneplus.odm.provider.PayloadProvider/OP_payload_upload_table
03-08 01:18:52.917: E/ActivityManager(1462): Invalid thumbnail dimensions: 0x0
03-08 01:18:53.003: E/ActivityThread(3135): Failed to find provider info for net.oneplus.odm.provider.PayloadProvider
03-08 01:18:53.004: E/AbstractTracker(3135): Unknown URL content://net.oneplus.odm.provider.PayloadProvider/OP_payload_upload_table

**Comment by codehz** [comment]
X.patch已经失效。。请手动更新代码，并合并更改。
这个错误应该在develop分支被解决了

**Comment by 940842546** [comment]
我用develop1.0编译的也啥软件都打不开 其中有一次微信出来过启动界面 但启动界面后立即黑屏 其他啥软件都卡打开中或黑屏 X.patch该怎么用呢
